name: test
on: [push, pull_request, workflow_call]
jobs:
  feature-matrix:
    uses: ./.github/workflows/feature-matrix.yml
  test:
    name: test ${{ matrix.package.name }} (${{ matrix.package.features }})
    runs-on: ubuntu-latest
    needs: [feature-matrix]
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.feature-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Lint
        # for now we are not too pedantic
        continue-on-error: true
        run: >-
          cargo clippy --package "${{ matrix.package.name }}" --no-default-features --features "${{ matrix.package.features }}" --tests --benches --examples --all-targets -- -Dclippy::all -Dclippy::pedantic
      - name: Test
        run: >-
          cargo test --package "${{ matrix.package.name }}" --no-default-features --features "${{ matrix.package.features }}" --tests --benches --examples --all-targets
  publish:
    name: publish (dry-run)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish crates (dry-run)
        uses: romnn/publish-crates@main
        with:
          dry-run: true
          resolve-versions: true
